### ISSUE TITLE
BitcoinTalk Thread

### ISSUE THREAD

**Issue by GT3000** [turtlecoin/meta#10]
We should probably put up a bitcointalk thread to generate excitement and curate information

**Comment by RocksteadyTC** [comment]
We have been looking for a respectably ranked member to create the thread and serve as our BTCTalk liaison as most of us use TOR which is blocked from access in most cases.

**Comment by editfmah** [comment]
I’m happy to do it,  but my rep is pretty low because I’ve only commented a few things.  But being UK based I have a level of government impunity!

**Comment by RocksteadyTC** [comment]
You're our guy then :)

**Comment by RocksteadyTC** [comment]
oops, didnt mean to click close

**Comment by ricardomarlus** [comment]
I was thinking about BTalk too. Can bring more people to contribute. :)

**Comment by RocksteadyTC** [comment]
@ricardomarlus great! be sure to contact @editfmah

**Comment by rcdmar** [comment]
Images for the post are finished. Uploaded them here: 
https://github.com/rcdmar/turtlecoin.lol/tree/master/brand/assets/special
I included the full _infographic like_ vertical version and also separate images as I understand there's info that needs to go inbetween.
Please let me know if I messed up any of the text and didn't notice. Thanks!

**Comment by RocksteadyTC** [comment]
This is everything I'd hoped it would be and more. Thank you @adjoining! @editfmah assuming this meets your approval as well, let's go ahead and get this up with some links to community services.

**Comment by editfmah** [comment]
So, after re-writing this many times.  Yesterday, with all the FUD made me think that people really need to get this coin.  People calling it a shitcoin really got to me, even though the reasons they have are valid, it kind of feels like that's the domain of people trying to pull a fast one, which we are not.

So I went with the pitch that we, know what we are, and sure thats how we will start.  But that is not where we will end up.

So this is a mockup PDF

@RocksteadyTC @rcdmar 

[ANN.pdf](https://github.com/turtlecoin/meta/files/1674347/ANN.pdf)

**Comment by BebopTC** [comment]
@editfmah I like it but I have really 1 change request. The 'About Turtlecoin' starts off the document and it is way too negative and focused on what we are not and comparing to shitcoins. I think that discussion is valuable but should be moved down, perhaps to the 'what are we doing differently' section.
Start the ann with positive, matter-of-fact statements about what TurtleCoin is without comparing to others or trying to defend from FUD

**Comment by editfmah** [comment]
Thats fair, i'm happy to make that change.  What would you consider to be the primary plus points to lead with?  My intention was that by acknowledging that bitcointalk is not reddit or 4chan, it would not be taken in a negative way.  So I would like to gauge it in a genuine way that people don't think is just a glossing over of the fact that it is another fork.  So would still like to avoid some of the more obvious positives that lots of the other coins do, if you see what I mean!

**Comment by BebopTC** [comment]
we don't really have a technology differentiation (yet) if we're honest. but we do have core development that works on the core service, we are not just a fork-and-forget copy of bytecoin - our code will evolve on its own, and we have upcoming projects to add interesting features (like mobius). so i think a core dev team that understands the algorithms, protocols and code working on the system is a worthwhile plus.
aside from tech, i think the biggest differentiation is community. 
we are very open, transparent, welcoming, and helpful. we WANT everyone to be able to contribute to the ecosystem regardless of skills or knowledge (or lack thereof) and are ready to help people do so. within just a few weeks, without any ICO or premine, without any marketing, without any capital, we've seen the community establish mining pools, native builds for mac and windows, trading via bots, trading on exchanges, GUI wallets for various platforms, public nodes, bots, blockchain explorers, number of tools and services, even selling clothing and trtl related merch... all of our logos, design, etc is from the community and we are happy to see people use it for entrepreneurship 
i think  some of that ties well into your point about the bounty system.
these are just talking points, they'll need to be refined and stated more succinctly but i think that is a big part of what we want to communicate.

**Comment by editfmah** [comment]
@RocksteadyTC @BebopTC ,

How do you feel about this as an opener.

Welcome to TurtleCoin, well at least the announcement of.  We would like to share with you the dream we have for the coin, what it stands for and where it could go in the future.  Sure it has humble beginnings, being a fork of ByteCoin, but already there is a thriving community behind it and a team of developers which is growing every week with some serious talent making contact to offer help.

So what are we definitely not, we are not a fork and forget coin.  We are already modifying the algorithms, and starting code-inroads into adding features and value to what the original ByteCoin had to offer.  With such unprecedented interest and offers of help so early on, we were initially overwhelmed and it has taken a while to marshal everyones efforts into the right areas to gain focus, with weekly updates on progress and who is working on what part of the project available on our blog.

Being incredibly open and transparent is important to us, we want to retain that sense of fun, and inclusiveness but also to build up trust in a community that has seen hundreds of forks of this codebase that offer little other than a name change, we hope the changes we make will be positive and keep us around in peoples hearts.

We want everyone to be able to contribute to the ecosystem regardless of skills or knowledge (or lack thereof), and we are ready to help people do so.  Within just a few weeks, and without any initial pre-mine, ICO, marketing or capital we’ve seen the formation of mini pools, additional builds for other platforms, block explorers, trading bots, addition to an exchange, public nodes and crazily even merchandise.

Some of these points will be refined below, but we really wanted to come out of the gates openly, acknowledge our humble beginnings but paint our vision for our future.

**Comment by JohnGoure** [comment]
You covered a lot of good points, however you have a lot of run on sentences and you are verbose. Grab a copy of "The Elements of Style" William Strunk. Here is a PDF http://www.jlakes.org/ch/web/The-elements-of-style.pdf There are a lot of great tips to help your writing style.

For example you say "Being incredibly open and transparent is important to us, we want to retain that sense of fun, and inclusiveness but also to build up trust in a community that has seen hundreds of forks of this codebase that offer little other than a name change." That is a huge run on sentence and you infer thoughts without bringing a clarity to the idea. 

Here is an example of a thought you express without bringing any clarity to it, "we want to retain that sense of fun", What sense of fun are you talking about? You didn't say the transparency is fun or the openness is fun. Therefore the reader is left asking what sense of fun are you referring too. 

This is a great rough draft. Perhaps go to your local university writing center and they can help you further along!

**Comment by editfmah** [comment]
@JohnGoure , thanks for the feedback.  Sadly, that is a trait I have had for many years now, and life does not afford me the time to indulge myself in any further curriculum outside of my profession.  Even WWDC has become a bit hard to fit in of late.

I have revised it based on your feedback, some of the points you make were more due to the fact that it's gone 1am here and actually they were just incorrectly developed sentences, that actually made no sense.

2nd revision:

Welcome to TurtleCoin, well at least the announcement of. We would like to share with you the dream we have for the coin, what it stands for and where it could go in the future. It has humble beginnings (being a fork of ByteCoin) but already there is a thriving community behind it and a team of developers which is growing every week.

What are we definitely not? We are not a fork and forget coin. We are already modifying the algorithms, and starting code-inroads into features adding value to what the original ByteCoin codebase had to offer. 

And with such unprecedented interest and offers of help so early on, we were initially overwhelmed, taking time to marshal everyones efforts and  gain focus, with weekly updates on progress and who is working on what part of the project available on our blog.

Wanting to be seen and fun and inclusive is great, but that can come across as being somewhat charlatan as well. So being incredibly open and transparent is important to us, to build up trust in a community that has seen hundreds of forks of this codebase, offering little other than a name change. 

We hope the changes we make will be positive and keep us around in peoples hearts.

Everyone is welcome to contribute to the ecosystem, regardless of skills or knowledge (or lack thereof), and we are ready to help people do so.  Within just a few weeks, and without any initial pre-mine, ICO, marketing or capital we’ve seen the formation of:

Mining pools
Additional builds for other platforms
A blockchain explorer
trading bots
inclusion on an exchange
public nodes 
and even merchandise based on our branding.

We love and encourage this level of entrepreneurship.

Please feel free to read on, we hope to see you all mining on our pools and talking with us on our Discord channel.

**Comment by RocksteadyTC** [comment]
I like revision two a LOT, very good approachable narrative style, and I think it breaks from the typical ANN's very well. Solid job, man!

**Comment by RocksteadyTC** [comment]
Post it!

**Comment by nurazhar** [comment]
Bitcointalk senior member here glad to help

**Comment by RocksteadyTC** [comment]
Thanks @nurazhar we could really use some help in our thread. Most of us are not high ranking on BTC Talk, and it's hurting our presence there. If we could have a BTC Talk community liaison present who also uses the TurtleCoin Discord chat, it would go a long way to helping relations with that community


- chat.turtlecoin.lol

**Comment by brandonlehmann** [comment]
Is this issue still required?
