### ISSUE TITLE
Looking for thoughts and opinions on markdown to static site generators

### ISSUE THREAD

**Issue by SoreGums** [turtlecoin/meta#102]
as you may be aware, we are working on creating a complete TurtleCoin branded  documentaion frontend for our single source of truth [docs](https://github.com/turtlecoin/turtlecoin-docs).

This thread is for people to highlight different tools we might be able to use to get the job done.

The other thread #98 is where we are discussing the look and feel aka the design that we want.

Cheers

**Comment by Sajo811** [comment]
*Copied from #98* 

Grav seems like dae wae to go.

I've gone through the available skeletons, and these two seem pretty good to me
[Learn2](http://demo.hibbittsdesign.org/grav-learn2-git-sync/advanced)
[Gravstrap](http://gravstrap.diblas.net/)

Learn2 because it gives off a nice impression of guides, and has the thing on the top letting you know where you are (like @SoreGums liked).
We could probably strip the checkmarks and the numberings from the theme for our purposes
We can also click on the top level links in the sidebar, which the current mkdocs doesn't support

Gravstrap because the navigation bar is responsive and scrolls down with you

Neither of them have a table of contents tho, which sucks :((

Out of the two, I'd choose Learn2 because of the stuff above, and it also has a search function.

I guess I'll keep looking tho :)

**Comment by Sajo811** [comment]
**SCREW GRAV**

**Comment by Sajo811** [comment]
**DO NOT USE GRAV IT'S HORRIBLE**

**Comment by Sajo811** [comment]
**YOU'LL SPARE YOURSELF FROM TERRIBLE THINGS BY NOT USING GRAV**

**Comment by Sajo8** [comment]
Whyd you close this?

**Comment by Sajo8** [comment]
#98 isn't resolved, should this be re-opened?
