### ISSUE TITLE
Open FPGA discussion

### ISSUE THREAD

**Issue by ghost** [turtlecoin/meta#116]
I have been doing some research on FPGA's and wanted to have a landing page for people that I have been researching with knowledge of hardware and software development to invite them to for discussions if they do not feel like joining the discord server.

**Comment by RocksteadyTC** [comment]
We should probably read this guy's entire site. It seems to be made for what we're aiming for, with respect to learning time. 

![image](https://user-images.githubusercontent.com/34389545/41890764-82dc8a44-7900-11e8-9bdf-4332520dd3d1.png)
![image](https://user-images.githubusercontent.com/34389545/41890775-9092c040-7900-11e8-8255-03f0c614016a.png)
![image](https://user-images.githubusercontent.com/34389545/41890785-9eaa4c48-7900-11e8-9e8d-18a6ae8e9c78.png)

**Comment by RocksteadyTC** [comment]
http://fpganow.com/index.php/2017/12/22/a-diversion-for-cryptocurrencies/
![image](https://user-images.githubusercontent.com/34389545/41890808-c21f1bea-7900-11e8-8b33-5b4d00823d2a.png)

We should probably contact John

**Comment by git-labview** [comment]
What kind of questions do you have on FPGAs?

**Comment by crappyrules** [comment]
@git-labview 
we have been discussing the merits of encouraging FPGA usage on the network **IF** we could come up with a way to allow miners to have multiple supply choices and open code/firmware.  We are in the speculation and research stage currently.  I personally would embrace the idea if the hardware was available from multiple vendors and the end user could flash their own code into the rig after pulling it from a github or similar repo.  Ideally I think that miners would embrace FPGA mining if the cost was lower or similar to the current GPU prices.  Seems like a pie in the sky endeavor though I would love to see it as a reality.

@JohnStratoudakis I will see if I can find someone with a more intelligent response to your question than I am able to provide.  We currently have begun the process of dissecting the entire code base for a complete rewrite and hopefully soon there will be more detailed documentation available.  Maybe @RocksteadyTC knows someone that can explain the CryptoNote algorithm for you?

**Comment by SoreGums** [comment]
@JohnStratoudakis the CryptoNote specs are here https://cryptonote.org/standards/ Light was supposed to do half the iterations...

**Comment by JohnStratoudakis** [comment]
@SoreGums thanks, I thought that it was missing something because the last update was in August 2014.
Half the iterations, not bad.

**Comment by git-labview** [comment]
@crappyrules 
1. Open source requirement - seems achievable
2. Multiple supply choices: FPGA chips are mainly made by Intel/Altera and Xilinx.  The boards can come from varying companies but most come from Avnet and Arrow (resellers of chip companies).  Avnet has a good FPGA guide (link is too long, just google term).  IP, there is opencores and other similar sites.  With FPGA dev you have PC drivers, IP, hardware so sometimes using a specific supplier tends to be advantageous (lowers risk).  I use LabVIEW FPGA which could be considered proprietary by your definition since you cannot run their logic on other cards.  Amazon has an F1 instance which is Xilinx FPGAs
3. FPGA cost of mining is higher than ASICs, lower than GPUs.  The bitwise nature of mining lends itself more to FPGAs than GPUs so in the long run this has a good chance.  GPUs have a lower barrier to entry but I believe the energy costs make them difficult.  I do not have numbers but any estimates have shown FPGAs to be very powerful.  The challenge is getting a board with the right amount of memory and I/O.

This guy http://zetheron.com/ seems to be among the first going into FPGA based mining.

**Comment by brandonlehmann** [comment]
This issue appears to have lost steam. Perhaps checking out the FGPGA discords would be a safer bet aeh?
