### ISSUE TITLE
Turtlecoin.lol verification on Brave Browser

### ISSUE THREAD

**Issue by SpoofytheWhale** [turtlecoin/meta#136]
Is there anyway we can get Turtlecoin.lol verified on the Brave Browser. The desktop version has the BAT rewards and enable users of the brave browser to tip websites with BAT. This would be awesome to get some extra funding to the project.

**Comment by zpalmtree** [comment]
Do you know how we go about doing this process?

**Comment by SpoofytheWhale** [comment]
https://brave.com/faq/#unclaimed-funds

**Comment by fexra** [comment]
I'm all for it, but who will receive the funds? I was thinking it could go to a fund to purchase turtlecoin.com?

**Comment by SpoofytheWhale** [comment]
Hell yeah! I believe a grant of 35 BAT is given every 4 months to users of brave with an Auto-tip feature. I know for sure I'm setting mine to Auto if Turtlecoin.lol becomes verified

**Comment by Sajo8** [comment]
Brave finally released their Brave Ads thing, which lets a lot of people earn some BAT. This would be a great idea, but I feel @fexra's question still remains; where will the funds go?

**Comment by SpoofytheWhale** [comment]
There are a lot of options to choose from. The turtlecoin.com site. Advertising such as social media platforms like facebook, instagram, snapchat. I have over 120 BAT i want to donate to turtlecoin. Any funding would help this project and with more people downloading the Brave browser this could be really beneficial to the growth of the project

**Comment by Sajo8** [comment]
Maybe we can use it to keep the tipbot up :wink:

**Comment by SpoofytheWhale** [comment]
That too. Maybe implementing a faucet on zpalms wallet. Almost like how NPXS has a faucet on theirs. On NPXS wallet it varies how much is given daily; for instance it can be 10, 16, 12 depending on the current value. This can bring more exposure to turtlecoins mobile wallet and ofcourse everybody loves free. @zpalmtree I know this is added workload, just thought it was a good idea lol

**Comment by SpoofytheWhale** [comment]
Just with my 120 BAT thats approximately  0.3 LTC - 411782 TRTL. Enough to spread some wealth :)

**Comment by Sajo8** [comment]
I feel that's getting way too deep into the monetary part of hings. A wallet is a wallet, not something you open up everyday and try to get free coins from. The tipbot was a joke lol, I can't think of something which needs "funding", since this is a doers market here. turtlecoin.com is owned by someone else and redirects to turtlecoin.lol, I don't think anyone here's going to buy the owner out. Funding sounds like a great idea, but when it comes to the actual point of it going somewhere and distributing it, I see it falling apart; there's not much of that culture here. Everyone does stuff because they want to do it, not because they want to get paid

**Comment by SpoofytheWhale** [comment]
I understand where you are coming from totally. The idea i mentioned was to draw people into turtlecoin. People love free stuff. When they get their hands on it, they become curious. For sure you'll see them transfer the trtl from one place to another and realize how fucking fast this coin really is. But ofcourse there is the issue with the domain... I need coffee

**Comment by Sajo8** [comment]
What's the issue with the domain? When I want to check a cryptocurrency's website, i look up their name, since I have no idea if their url is `crypto.com` or `getcrypto.com` or `getcrypto.org` or `crypto.io` or anything of the sort. The domain `turtlecoin.com` is owned by someone, and is being redirected to `turtlecoin.lol`. Will that be the same in the future? Probably. Is it guaranteed? No. All references to the website are turtlecoin.lol, and will stay that way.

**Comment by BrandonT42** [comment]
If I may put my opinion out there - receiving funding in any way, including tips via brave, sort of goes against the foundation morals of the project. We've gotten this far without any funding, and we will continue to go further without any funding. Introducing funding of any sort is asking for trouble - who gets it? What's it going towards? Who's gonna audit that? What would we even need funding for that word of mouth and volunteering time won't or hasn't already been able to achieve? It's a can of worms, and I don't think there should be any official means of accepting donations or funding, although I do appreciate the kind gesture.

**Comment by LeoStehlik** [comment]
“Draw more people to TurtleCoin with free stuff”. Nah. I seen it in other projects recently. It sounds a bit like buying followers on Twitter. The number of followers looks great on paper, but brings little to nothing to the project. There is no shortcut to grow the userbase. Slow & steady!
