### ISSUE TITLE
Chukwa: The Argon2 PoW Algorithm

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/meta#141]
Let's discuss the proposed next Proof-of-Work Algorithm based on Argon2id (codename *Chukwa*)

Blog Article: https://blog.turtlecoin.lol/archives/the-quest-for-decentralized-proof-of-work/
~~Branch: https://github.com/turtlecoin/turtlecoin/tree/codename_chukwa~~ Has been merged into the current development branch
Benchmark Test Results: https://github.com/turtlecoin/turtlecoin/issues/716
Speadsheet Form: https://docs.google.com/spreadsheets/d/1TJVqJsDCswgdTvtkhJfrg09rQAV9KifUKC2KDg0WkMc/edit#gid=1912293181

Related to #74 

Please provide your feedback and thoughts regarding the adoption of this PoW Algorithm.

Remember to always be a good Turtle 😃

**Comment by brandonlehmann** [comment]
Added article link :)

**Comment by bobbieltd** [comment]
I got banned on TRTL discord and can not know in dark next change. Is it pro-CPU and anti-GPU ?

**Comment by SoreGums** [comment]
it's pro distributed proof of work.
gpu miner is being worked on, cpu is good to go.

**Comment by RaulDukeNukem** [comment]
> I got banned on TRTL discord and can not know in dark next change. Is it pro-CPU and anti-GPU ?

If I were a betting man, I would say you were banned due to the **coin-dumper** in your discord screen name.  The **turtletard snowflakes** are easily triggered at the slightest hint of market talk.  No jury in the echo chamber.  It is their way or the highway and they do not care who they upset of offend.  I dumped my bags of their shit coin at over 6 sats and will refrain from buying any more in the future.  It is impossible to invest in a currency that even the developers themselves do not want to buy.  TurtleGold will be a hard fork of the existing chain and add actual value to the network.

**Comment by brandonlehmann** [comment]
Implemented in PR https://github.com/turtlecoin/turtlecoin/pull/851
