### ISSUE TITLE
Dynamic Fee Algorithm for TurtleCoin, Discussing 'Fee Factors'

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#145]
Other networks are getting large amounts of minimum fee transactions, and this is causing some congestion issues in incidences when the fee is low enough to make a low cost denial of service possible. While this is currently an issue limited to other networks, it may make sense to discuss, given our low static fee and fast blocks that still make such a scenario possible.

## What is this discussion for?
Forming a list of possible variables in a Dynamic Fee Algorithm is a good first step in forming a fee system that works best for stability of the network. Once all influencing factors have been considered, we can move forward with the moving parts and details of how the variables will be treated. This is about getting the whole picture, not about analyzing outcomes.

## What topics are best for another meta thread?
I'd like to keep this conversation limited to the discussion of the development of a low fee algorithm. Tangential debates will be removed. This is not the place to discuss RPC blocking and threads in the daemon, though they may be related and may be worth fixing, they're not the topic of discussion.

## The current situation as it stands
Fees are very cheap leaving us open to TX floods, (0.1 TRTL) 
Raising the static fee for everyone would unduly burden every user,
Not all transactions have a fee (fusions must be processed)
Not all transactions are equal (some have a few inputs, some have a lot.)

#### Things that have an influence on the effort-cost of processing a transaction
- number of inputs in a tx
- number of inputs in previous block
- is fusion? (fusions are free)

^ this is the list of factors this thread should work on expanding.

**Comment by brandonlehmann** [comment]
<reserved for expansion later>

I’ll get into detail later but I’ll present a solid counter argument.

**Comment by SoreGums** [comment]
what if there was simply a processing factor and it is a measurement of how long it takes to process a tx. as the measurement is done on any device, a coin base transaction is the benchmark, if device1 takes 1sec to process it and then to process this new transaction it takes 30secs, well this new transaction has a processing factor of 30x.

I'm proposing that while there are obvious factors as mentioned, the overall issue is related to actually processing and storing transactions has a cost. so just measure those things and come up with a calculation that adjusts the priority of transactions. there is more to write here however to keep on topic.

* measure how long it takes to process a tx and compare it against a coinbase tx and have that be the weighted factor in determining this tx priority in the queue aka fee

**Comment by brandonlehmann** [comment]
A coinbase transaction has no (zero) inputs and requires nearly zero validation separate from the block. That’s will never be a valid measurement for a baseline. 

Even if it were, how would you establish the baseline as applied to the rest of the network? What hardware establishes the baseline? It can’t be relative based on the each nodes’ processing as some transactions where the fee is acceptable may not be acceptable for others. 

Transactions are already prioritized by fee, size, amount, etc.

**Comment by SoreGums** [comment]
as the factor is multiplier then it should work out on any device.

each device does the calculation and should get similar results.

if coinbase is not significant enough then designate an existing transaction as the baseline and compare against that.

running on my 500MHz machine i get all the data needed and run the calcs for the baseline tx (thus removing i/o from the equation) i get 129ms. then this becomes the baseline for this device. all new transactions that arrive are now measured against 129ms. if the tx comes in at 1290ms it is a 10x.
on a 3GHz machine it might be 10ms and 100ms, still 10x...

**Comment by brandonlehmann** [comment]
Just so we’re clear, you’re suggesting picking an arbitrary transaction to baseline network consensus and fee scaling on? This model would require accounting for variations in hardware due to more than just CPU speeds (instruction sets, I/O speed, data fragmentation) — the fact that validating inputs does not follow a linear resource utilization, etc.

**Comment by brandonlehmann** [comment]
Also, your update to your first post highly relies on relative measurements on arbitrary hardware. The complexity this would impose for people to understand how much it costs to send amount x to party y promotes a poor user experience that it’s “fun and easy” IMO.

**Comment by SoreGums** [comment]
yes, drawing an arbitrary line in the sand and the whole network is now agreeing that is the line, same as all the other consensus rules...
I'm suggesting to narrow down the resource usage to CPU by getting all the data before measuring.
the daemon does the measurement on startup and holds that number as it's 1x and now measures everything else against it.

When I read your messages it seems like when I say each daemon compares within itself you're thinking I'm saying compares to each other. A wallet can do the same measurement as a daemon. 

No human needs to figure anything out. this transaction with a million inputs and takes up a whole block simply takes longer to process than the baseline transaction with 5 inputs byu a factor of 100x, so the network if busy is probably going to de-prioritise your transaction if things are busy.... this seems straight forward to me under my operating assumption of all devices can arrive at multiplier factor as measured by them.

**Comment by brandonlehmann** [comment]
You bring up an interesting point in assuming that everyone runs the daemon on the same machine as their wallet. What about the discrepancy between the wallet machine and node machine to establish 1 unit? My wallet machine says this 1 unit but the node I’m using is slow and says it’s 20 units. Sure I can use a different node but now that node will drop the transaction when it’s relayed to it?

Also, to accept the transaction on the network, every daemon would have to compare to all other daemons in some form or as you said the transaction gets dropped. Then you have a segmented transaction pool where some transactions are valid on some nodes and not others. This is exactly a consensus issue as you said but you’re introducing, what I feel is, convolution to the consensus mechanism for little to no overall benefit. 

Absolutely a human must be able to figure out what the fee is regardless of a wallet doing the math for them. I know right now that at minimum, every transaction I send costs 0.1 TRTL unless I want to pay more to prioritize it. That’s pretty easy to understand.

This isn’t accounting for the fact that the baseline has to be recalculated regularly to account for changes in hardware. That means that transaction fees are a moving target which makes it very difficult for users to conduct business on the network of the costs keep changing.

**Comment by SoreGums** [comment]
the baseline is per cpu, each cpu determines its own baseline.

like current cpu benchmarks on review sites, they explicitly state on this exact hardware this baseline cpu2 and this other cpu2 are different by x. then they measure a new cpu3 and its multiplier of x against the baseline cpu1. those multipliers should be pretty accurate if a different person sets up up all different hardware with the exact same cpus should get near identical multipliers for cpu performance running the same cpu tests.

i'm not sure how to say this differently. each thing, a wallet, a daemon, whatever that needs to calculate the processing-factor needs to:

1. go get the network designated baseline transaction
2. calculate how long that takes to process in its operating environment, i'm saying focus the measurment on cpu, get all the data beforehand so that data stored on 1mbps bus has zero impact.
3. hold that value for as long as the process is running as 1x, lets call it 10ms
4. whenever a new transaction comes along or is created run the measurement and compare against its 1x value of 10ms. if the new thing took 20ms, well now this tx is a 2x

this 2x should translate perfectly to other hardware

1. on other hardware
2. process starts and it grabs the network designated baseline transaction and measures how long it takes to calculate and arrives at 1000ms is its 1x
3. that 2x transaction arrives from before and now it is processed and measured and it comes out at 1998ms, that's a 2x, things match.

what am i missing here that you keep coming back with "different hardware has different results, this kitten rolled a watermelon out of a lake..."

**Comment by an3ki** [comment]
I think the network/users would understand when the network is under pressure the fees need to be dynamically lifted to a certain degree.

The attackers typically use .01 for a flood, if the fee is raised to 10.00 for anything under 9.99 during high network usage, I think people would understand as it is more of a security measure to protect the network rather than punish the user. 
The general user will most likely not be impacted as the majority are not sending transactions under 9.99.

**Comment by SoreGums** [comment]
> The attackers typically use .01 for a flood, if the fee is raised to 10.00 for anything under 9.99 during high network usage, I think people would understand as it is more of a security measure to protect the network rather than punish the user.

that's not really how it works though...
transactions get sorted in the mempool.
once there are enough transactions, the ones at the bottom of the stack get removed.

so if your transaction of a lower fee compared to all other transactions survives riding the bottom of the pile, the tx will make it into a block _eventually_

**Comment by an3ki** [comment]
ahhh ok, that makes sense, thanks for painting a clearer picture

**Comment by brandonlehmann** [comment]
> the baseline is per cpu, each cpu determines its own baseline.
> 
> like current cpu benchmarks on review sites, they explicitly state on this exact hardware this baseline cpu1 and this other cpu2 are different by x. then they measure a new cpu3 and its multiplier of x against the baseline cpu1. those multipliers should be pretty accurate if a different person sets up up all different hardware with the exact same cpus should get near identical multipliers for cpu performance running the same cpu tests.
> 
> i'm not sure how to say this differently. each thing, a wallet, a daemon, whatever that needs to calculate the processing-factor needs to:
> 
> 1. go get the network designated baseline transaction
> 2. calculate how long that takes to process in its operating environment, I'm saying focus the measurement on cpu, get all the data beforehand so that data stored on 1bps with a latency of 4hrs per request bus has zero impact.
> 3. hold that value for as long as the process is running as 1x, let's call it 10ms
> 4. whenever a new transaction comes along or is created run the measurement and compare against its 1x value of 10ms. if the new thing took 20ms, well now this tx is a 2x
> 
> this 2x should translate perfectly to other hardware
> 
> 1. on other hardware
> 2. process starts and it grabs the network designated baseline transaction and measures how long it takes to calculate and arrives at 1000ms as its 1x
> 3. that 2x transaction arrives from before and now it is processed and measured and it comes out at 1998ms, that's a 2x, things match.
> 
> what am I missing here that you keep coming back with "different hardware has different results, this kitten rolled a watermelon out of a lake..." I feel like i've addressed different hardware gets different results by mitigating that in the OP and with a consistent msg in each reply. the baseline is done per cpu, all that is shared is the multiplier, each cpu needs to figure out its own baseline using the designated network defined baseline transaction.
> 
> the rest of the post doesn't make sense as long as we're talking about different things 

Claiming I’m using a red herring is weak. 

The fact of the matter is you haven’t addressed it to my satisfaction as from my point of view you’re missing consensus fundamentals that explain the full scope of what you’re suggesting. I’m also of the firm belief that it’s ***a horribly bad idea*** because it’s adding unnecessary complexity and more risk elsewhere to solve an issue that can be addressed in smarter ways. 

I’m exiting this conversation. 

If you want to build it this way, go for it. Let’s us know when your code is ready.
