### ISSUE TITLE
Japanese Turtlecoin Website Translation

### ISSUE THREAD

**Issue by truthwillsetyoufree** [turtlecoin/meta#27]
I shared it on the Discord, but I'll just drop it here so anyone can access it at any time. I think it would be great to raise awareness among the Japanese market. 

https://docs.google.com/document/d/1ZgGii9r7t34lFQ1GSmDUlgORSdqHEzXdQV6Hq8wSRKQ/edit

**Comment by RocksteadyTC** [comment]
We are now working on the best way to integrate the translations, we may need your help proof reading after. Thank you!!!

**Comment by holmholk** [comment]
@truthwillsetyoufree 
I read your translation and I found a lot of bad word choices and wrong sentence structures.

For example: For the translation of "TurtleCoin is Safe", I'd use the word anzen(安全) instead of bunan(無難) in this context. The word "safe" in this context means security-wise safety but your translation is like "It's a safe bet. It's not the best nor the worst. It's a compromised option", which slightly includes a negative connotation. It's not something you want to say to your own product when you want to promote it. 

I'm from Japan, a native speaker of Japanese, so I think I can do a better job of proof reading or translating it :wink:

**Comment by truthwillsetyoufree** [comment]
@holmholk 

Ok! If you would like, I can give you editing privileges on the document so you may fix any errors you see.

**Comment by brandonlehmann** [comment]
Do we have any takers on Japanese translations? Otherwise, I think we can close this up as other translations have been completed.
