### ISSUE TITLE
Cryptocurrency 101 Primer

### ISSUE THREAD

**Issue by GT3000** [turtlecoin/meta#38]
Since TRTL is likely to be many people's first foray into mining, owning, and learning about crypto, I think it would serve us to respectfully provide a baseline understanding of what cryptocurrency is, the different kinds of coins (Proof of Work/Proof of Stake/Proof of Capacity/Masternodes/ERC20/Proof of Burn) to better inform people about crypto. A short primer would help those who either don't know or misunderstand certain facets of crypto be better informed.

We could also potentially cover the major algos like Cryptonight, SHA-256, etc. 

Thoughts?

**Comment by gigantomachia** [comment]
I think a better onramp would be helpful, and a tutorial on crypto could certainly be part of that. Honestly, I think for most people a basic primer on bitcoin and cryptocurrency would touch on what the blockchain is, what it allows, why the incentive structure is important, proof of work, and SHA-256. Maybe it’s worth mentioning there are other methods to mine a new block (proof of stake, etc), but you risk losing people if you start getting into much more. I think it’s worth talking about the privacy aspects of Bitcoin vs TRTL, and also how Bitcoin differs from Ethereum. Since I come at this from a non-technical perspective, I feel like I have a good sense of what information is important for a layperson to understand the basic concepts, and what information is superfluous and adds unnecessary complexity if the goal is just to teach someone about what crypto is.

**Comment by ac1984** [comment]
Just as a side note I really liked this for Stellar https://novicedock.com/learn/cryptocurrency/stellar. There is one for Monero there too - https://novicedock.com/learn/cryptocurrency/monero

**Comment by SoreGums** [comment]
All sounds great, some other thoughts.

Focus on the practicalities, then sprinkle in some theory.

Great you want to get in on this 🐢 coin thing, download this. Now you need somewhere to keep these coins, it's called a wallet, it takes care of things. Now this is important, you lose access to your wallet, you lose the coins it contains, just like a physical wallet with cash in it. So how do you make a backup? Well there are three things you need and they are just letters and numbers, they look like this.... So grab a piece of paper and pen or get your password manager ready to make a copy of your keys and address....

Keep going like that.
It is giving the theory at the same time as the practical steps. If someone wants all the theory it is already out there, they would get it already if they were interested, etc. Sprinkle in some links through the main site if need be. The point I'm making is the combo theory+do this now = best outcome.

**Comment by brandonlehmann** [comment]
Did anything come of this? If so, please feel free to re-open it.
