### ISSUE TITLE
Madk's Mesh Network Idea

### ISSUE THREAD

**Issue by RocksteadyTC** [turtlecoin/meta#46]

**Comment by krruzic** [comment]
Pasting all the thoughts I previously posted in discord here for easier reading. 


"Anyone around
I legitimately think I stumbled upon an amazing idea
It's a general purpose distributed p2p network.
that means file sharing, payments, network access (to the internet), file storage
whatever else."

"asset creation and management.
no
tor is part of it
tor does not provide what I'm imagining
tor would be like an extension or module of it
the best part is the network is self propogating
and the cost-benefit analysis is in its favour automatically. Everyone will WANT to run a node."


"its core is through a mesh network. Built on top is a distributed ledger like a blockchain. It's a protocol that's easily extensible and upgradeable with WHOLE network consensus
oh and 
nonironically solves the oracle problem
it handles consensus for transactions and network usage at a constant rate with local (nearby) peers and then publishes blocks to a randomly elected masternode which then verifies with a random masternode on different local network
I imagine the local networks and neighbourhoods
there could be more tiers I don't know but 2 tiers is pretty good
in the beginning the network would have to be centralised. However at a certain point that feature would be announced and removed in verifiable updates. Peers would agree it removed the feature and switch to the new consensus method."

""How does it self propogate?"
Provides Tor like access to the internet in general for essentially minimal or ZERO cost and eliminates censorship attempts for any usage.
A $100 or less kit to become a peer with meshnet gear would be sold online and door to door
and initially through a fundraiser
as long as the initial distribution took off this thing would be unstoppable
anyway, if anyone wants to discuss this or thinks it sounds cool let me know
the basic concept relies on providing more benefits than cost at the very beginning. No one wants to run a bitcoin node because it doesn't benefit them in any way. This is different."

"no NO
ipfs is nothing like this
it has no consensus method
it is not general purpose
this provides a consensus layer for general purpose networkihng
meaning I can publish a site (like ipfs) and still update it
ipfs is a part of it
just like tor
GENERAL PURPOSE
TRUSTLESS
those are the key words
and no, it's not a smart contract platform because those are pointless. extensions can be written and willing users can install them and interact in a subnet at FAST speeds
and computing ANYTHING that makes sense.
That's what the asset platform could be. WAVES would be an extension.
that provided such a feature. I don't want that so I don't run that extension
as long as my masternode ran it I could run it. And since masternodes are random, as long as you have a local peer you will eventually (in minimal time) be able to globally publish your transactions"

Something key to this is having 2 tiers of networks: A local one with peers on your meshnet with near instant transactions. These local nets would be small enough that tx/s would be max 10. Outbound Transactions (heading to other 'local networks') would be sync'd by randomly elected masternodes and published at set blocks. These masternodes would be tasked with communicating with some portion (or all?) of the other masternodes and handling tx in traditional blockchain manner. Basically a local net should be able to validate local txs without having to know the whole state of the network

Actually no one ever should need to know the whole network state (back history).

**Comment by editfmah** [comment]
So if you had a blob object, that would not exist on all instances of the blockchain?  It would exist in elected nodes?  You would almost be better off writing client software that stores aes encrypted chunks of everyones data, then use the blockchain to validate and verify the locations of those chunks.  But then you would be better off doing that with distributed sstables anyway as they are built for that purpose and are decentralised also.  Adding some kind of blockchain verification to cassndra would give almost exactly the same benefit, but with far greater distribution potential.

**Comment by brandonlehmann** [comment]
Scope creep ?

**Comment by SoreGums** [comment]
been open long enough to get thoughts, if needs to be re-opened can
