### ISSUE TITLE
turtlecoin.lol technical revamp

### ISSUE THREAD

**Issue by ghost** [turtlecoin/meta#47]
Hello, this is my first contribution to 🐢 . Really excited. These are my thoughts on making turtlecoin.lol 'technically' top notch and easy to work with. And also thinking ahead a bit :) I started out with some random spikes [here](https://github.com/turtlecoin/turtlecoin.lol/pull/8), but am open to changing it drastically based on whats discussed here.

1. Make development easier
    1. Use a templating engine like handlebars for server side rendering. So that html can be re-used via layouts, partials.
    2. `SCSS ` for better CSS management.
    3. Use babel for ES6 transpilation.
    4. Add linting, editorconfig
    5. Live reload based development workflow.

2. Keep the barrier to entry low
    1. handlebars is just HTML with additional tags. So just plain HTML works. Ditto SCSS.
    2. The tooling would increase the barrier to entry which we would mitigate by extensive documentation.
    3. Keep the toolchain JS based, since most frontend folks know that.

3. Support localization.

4. Automate deployment
    1. Automatically deploy merges to `master` to someplace (`gh-pages`, surge, netlify).  

5. Review apps
   1. Create a 'review app' when a PR is opened, so it can be easily previewed before PR sign-off.

6. Misc pages
   * Allow creation of markdown based pages (for [docs](https://github.com/turtlecoin/docs/issues/11)). Not sure if there is a use-case for this.

7. Optimize for SEO and [PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=turtlecoin.lol)

8. Optimize for social sharing
   1. Twitter cards – https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
   2. Facebook previews – https://developers.facebook.com/tools/debug/sharing
   3. Other og tags

**Analysis paralysis**

1. Whether its best to use lightweight static-gen JS tooling and custom stitch everything (like in the PR above), or use a full blown JS framework like [EmberJS](https://guides.emberjs.com/v2.18.0/) which does everything and is well documented but has a slightly higher barrier to entry.

2. Deployment: I've personally used [Netlify](https://www.netlify.com/open-source/) and it works very well (like doing a review app per PR via CI). Not sure if we want to just go with that or if we want to explore doing the same with `gh-pages`, surge etc.

Lets discuss!

**Comment by ac1984** [comment]
Re: Ember.js - **If** we decide on that, I can anchor that. Playstation Now, Apple Music, nasa.gov (among [others](http://builtwithember.io/)) are some examples of it.

**Comment by fexra** [comment]
I like the suggestions. I think we should prioritize SEO and localization as soon as possible. Regarding handlebars, I see no issue. May force someone to learn something new :)

**Comment by ac1984** [comment]
Added (8) - Optimize for social sharing

**Comment by ac1984** [comment]
I see that the site [started out](https://github.com/turtlecoin/turtlecoin.github.io) with Jekyll. We could use that too. Just that we won't use GitHub pages auto compilation -- since its is very limiting. Then we would build (gitignored) and publish to it via CI or a `rake` task. This would go against (2 iii) though.

**Comment by ac1984** [comment]
I really like the Forknote setup. One static site to rule them all – marketing, docs, blog etc. 

Technically the Forknote setup is old school (nanoc :)) but simple and pragmatic. JS tooling (outside of JS frameworks) does complicate things. Today's equivalent of this would be using `middleman` and housing all such sites under it.

**Comment by ac1984** [comment]
.. where blogs, guides, docs are all markdown based.

**Comment by RocksteadyTC** [comment]
@BebopTC

**Comment by RocksteadyTC** [comment]
https://github.com/turtlecoin/turtlecoin.lol/pull/8
For reference @BebopTC

**Comment by BebopTC** [comment]
I like to be consistent with the message that this is a doer's market. ultimately any project you start or fork is in your hands, you have absolute power to make any technical choice or design decsion. That said, turtle.lol is a singleton entity that represents the community as a whole so we have to be a bit more particular about the considerations. It's great that you queried the community for feedback because we certainly should when choosing a sight to represent us.

As far as tech stack goes I don't really care personally how it is built as long as it is reasonably easy enough for people to contribute both content and feature and the original content (blog articles, images, page content, etc) is statically maintained in version control - not stored in database or outside service.

A more modular system would be great! It could be a static site generator or something similar, or like you hint at something more rich with templated views, custom dynamic components, etc. I just ask you pick a lightweight framework that is easy to use and easy to break out and run with the generated code (in the case of static generator). Indeed i was using Jekly for turtlecoin.github.io - it's going to be remade 
into the "dev site" at some point but other priorities got in the way. It was really something I just threw up ASAP in a hurry to get some kind of page and doc up on our release and only having to push git commits was a win.

I would prefer not to *depend* on any outside service or CI for the site to build, but if you set one up for convenience I'm fine with it being used for convenience. That said, going along your mention of babel, linters and hot reloading I would lean toward webpack and npm scripts to do a simple build into static assets that can then be pushed to a static host we already have set up. I like webpack and npm over gulp or grunt for things like this. Keep it simple.

As far as ember, i only ever glanced at it several years ago. if you want to use it to for rich UI components etc that's fine. react and vue are more popular I think and I've used react some myself but people can always learn just enough ember to hack at the site if it is kept structurally simple. If it is too hard for volunteers to figure out and maintain it will probably get replaced by another codebase sooner than later.

Keep in mind the main site is mostly for 'marketing' and presentation, aimed to direct people to try the coin and check out the various projects. That's the main objective So prolly doesn't need to be very heavyweight.

As far as docs feature, it would need to pull its content from the official documentation repo ([github.com/turtlecoin/wiki](url)), which will be github style markdown. You (or a contributor perhaps) could set up something to parse the markdown files, build the documents into your own ui components and style their presentation with the theme of the site.  That would be cool, a TurtleDoc docs viewer. 

Thanks for all your help and for opening up to community feedback before starting. It's always easier to ask for forgiveness than permission in the software market ;-) I'll try my best to check out your commits and see if I can assist in any way, a turtledoc viewer markdown component sounds like a fun project anyway.

Happy Coding.

**Comment by ac1984** [comment]
> A more modular system would be great! It could be a static site generator or something similar, or like you hint at something more rich with templated views, custom dynamic components, etc. I just ask you pick a lightweight framework that is easy to use and easy to break out and run with the generated code (in the case of static generator).

> I like webpack and npm over gulp or grunt for things like this. Keep it simple.

@BebopTC Yep those were my instincts as well, hence I went with `yarn`, `webpack` and [metalsmith](http://www.metalsmith.io). I think its as simple as it gets. Alright I'll ping me you on the PR when its ready. 

Thanks!

**Comment by SoreGums** [comment]
Translation foundation out of the gate with subdirectories [1] and hreflang tags for Google would be ideal.
Nothing says c'mon in, like reading about something in your native language - opportunity for community involvement here as well ;)

[1] turtlecoin.lol/de/, turtlecoin.lol/cn/, etc

**Comment by cptcrunchy** [comment]
In line with @ac1984 and perhaps with what @BebopTC stated. We could look at [GATSBY](https://www.gatsbyjs.org/) to provide a static site generator with a relatively easy learning curve and is very well documented. I have a personal vendetta with Bootstrap, so if we could move away from using that it would be nice. I would be happy to make a Fork of the site and then present my working test module. If other devs enjoy this then maybe we can come to a consensus and make a switch. Just my $0.000000002 TRTL coins.

**Comment by ac1984** [comment]
Hi @cptcrunchy! I have something in the works, will run it by you shortly.

**Comment by RocksteadyTC** [comment]
Is this still in use https://github.com/turtlecoin/turtlecoin.lol/pull/8

**Comment by ac1984** [comment]
@RocksteadyTC Nope. You may close that.

**Comment by CryptoCutter** [comment]
I started a Telegram Group to promote Turtle Coin and and my friend Paul is simplifing the process for mining with easy to read directions and technical suppprt, all to help promote a great coin project with huge potential.

If any of you guys have a bit of time to check it out, and maybe offer some information to help us understand the project better we would love to have you.:)
https://t.me/joinchat/Hc9YkRJsFYFrlPQ2S9pjKg

**Comment by ar-x** [comment]
@RocksteadyTC Can you close this issue. Everything has been sorted out here. I'm the `ghost` here, so can't close it myself :(
