### ISSUE TITLE
Core vs. Community projects

### ISSUE THREAD

**Issue by mikeyb** [turtlecoin/meta#61]
Bringing this from discord.

I feel it would be a bit better if the main org repo did not have community contributed projects listed until such a time that the project has been tested, audited and verified by core team.

Community projects are great, and generally help the growth of networks.  But this should be done in such a manner to not cause confusion among users, while also making sure the user experience is the safest it can be.

**Comment by nnamon** [comment]
Some feedback from users indicated that separating officially supported turtlecoin projects from the more informal community provided projects may improve the first impressions of a potential user.
Additionally, this will build trust and reassurance in the provided software.

Some relevant comments:

MikO:

*"Just an opinion.  Asking for donations on a repo in main network github org seems a bit....lame?  greedy?  It is also concerning the app is from a non org dev.   This is in reference to (desktop-xamarin).   Just thoughts you may want to consider for external appeal to technical user base"*

*"If you want to present TRTL in such a way when people go look at the official apps on the repo they feel like the concern is over money rather than a usable network, so be it."*

*"If you want to ask for donations, maybe throw it a bit down on the README so it doesnt appear to be someone slapping software together to get donations."*

*"If donations are wanted for development, it would be much better to setup a general donation fund that is distributed to devs as they complete tasks."*

*"In my goat opinion, keeping contributed software out of main org repo is ideal.  A page or repo with readme that links to community projects is wonderful."*


Cassius:

*"For me a related issue is the extent to which software can be trusted, is seen as 'official' etc. I'm a big fan of the grassroots nature of the project, but at some point in the near future if things scale then there's going to be a lot more on the line for a lot of people. That can happen fast in crypto"*

*"TRTL's community and informality is a huge strength, but you do not want to be a victim of your own success. I'd suggest being clear about what comes from the team, and therefore what they are happy to take responsibility for - whilst of course being appreciative of third-party contributions. I don't know what kind of audit software goes through before it's included. The reality is though, that if TRTL grows to any degree, then people are going to be moving/storing significant amounts of value. Putting those at risk is not an option. Informality =/= unprofessionalism. And, as Miko says, donations to pay bounties or dev tasks is a good thing."*


Xhodan:

*"I like the idea of having core and community stuff in their respective categories. As a newer user here i can say that it's pretty confusing deserning what's core and community. It all just seems a giant pool of things going on at once."*

**Comment by nnamon** [comment]
I agree that segregating the officially supported repositories from non-official community repositories would be a great idea.

In the vein of a grassroots movement, we should also seek to adopt non-official community repositories into the official repositories list if there is a need to. A process should be put in place to ensure code quality and to maintain the good image of the project.

**Comment by xhodan** [comment]
I second the motion for segregation of official from non-official.

**Comment by ac1984** [comment]
I second this as well.  

Though I also see the importance of showcasing all community projects in one spot to increase participation in them. Maybe via a separate GitHub org called `turtlecoin-community`.

**Comment by RocksteadyTC** [comment]
TRTL addresses can go wherever the author feels it should go. Nobody is stepping over any lines, in this regard. 

I agree that community submitted projects should be clearly identified, with a link to the risks associated, but I do not feel this warrants their removal from the main organization repository. 

I would not be opposed to core team reviewing code for major version releases (considered LTS releases) of community projects, but I do not find it realistic to ask to occupy core members for this level of review for every update. 

Let's be careful with these sporadic community causes for concern, and not let them run away with our productivity and community spirit. There is a way to remain respectful of other's investments while not turning this into a mess of oversight. 

While I feel @mikeyb has some good points, I do not want this type of kick the door open and make demands approach to be common in the dev channels of Discord. Calling devs "lame" and "greedy" crosses a line as a newcomer to the community because you lack context, and it does not further your point. For context, I told that dev to put his address in the documentation.

The meta forum is the place for these proposals, especially when the involved parties feel passionately about them in the moment.
