### ISSUE TITLE
Move GitHub updates to a locked #repositories channel

### ISSUE THREAD

**Issue by fexra** [turtlecoin/meta#64]
I propose that we move the GitHub bot to a new locked channel named #repositories, #updates or something along those lines. Currently the #dev_general is being flooded by GitHub updates. Don't get me wrong, I'm very excited to see all this activity! However, it's making discussion harder, and many conversations are getting lost. 

I think this is a good solution because the people that want to see the updates can go to the locked channel and read the updates without our conversations, while the development team will regain better oversight on the conversation.

**Comment by paulie-g** [comment]
The value of updates in the main channel is that I, for one, have been alerted to a number of issues which I otherwise wouldn't have. Simply not enough time or attention span to check and backscroll another channel.

-1 from me.

**Comment by adj-gh** [comment]
**Suggestion: Massive Discord overhaul**

I think with the current state of the channel we should start thinking about making the discord a more organized place altogether. From a marketing perspective, having a well knit community instead of one segreggated by interests is better.

1. A different approach at user roles:
Essentially my idea is to add a different set of roles to the server. Required ones would be
-`@user`
-`@trader` 
-`@helper`. 
More could probably be useful.

2. A better distribution of servers
The roles above would allow for a better understanding of the different channels in the server and a more polite way for users to interact.
A person just entering the server for the first time would be introduced to view only `IMPORTANT` `GENERAL` sections where different channels could be
- **Important** would contain different channels that remain view only for every user, such as #welcome, #announcements, #faqs, #releases. One of this channels, most likely welcome would have a quick start guide on a self assiging the `@user` and/or trader role to get on the other channels. 
-**General** would mostly contain the #general, #help, #mining, #off-topic, #memes and all of those channels.
-**Development** would contain all current dev channels, but be placed above the General section. The #dev_ prefix could also be dropped. #dev_general could become #progress or something.#repos would go in here as a view only channel for the GitHub bot.
-**Bots** section for #pricecheck, #wallets, #rainbot, #network. It's been talked about how the current bots could be on their own self updating channel. 
-**Markets** for #trade, #turtle-market, #exchanges. `@trader`s would be able to view and discuss in this section.
-**Exile** because of the constant rattling of cages down there.

3. Modifications of the current Turtle bots
For above said purposes, a few changes would need to be made to the bots. Self assigning roles is something @SoreGums has some insight to. 

Thanks!

**Comment by RocksteadyTC** [comment]
I have agreed to test out the compromise of moving meta to it's own output channel, however, since it is no longer a single rule stating "pipe all GH activity to our single channel," you'll need to give me some time to figure out the best way to go about this.
