### ISSUE TITLE
TRTL 2 decimal design and users expectations around price

### ISSUE THREAD

**Issue by ghua78** [turtlecoin/meta#67]
After discussing two digits design today on discord, I think we should make it totally clear about what can be expected from TRTL in terms of price. I think many people who are not very familiar with crypto coins may have an impression that it is possible for TRTL to reach $1.

As Zpalmtree pointed out it would lead to cap 1 trillion while BTC has only 181 billion atm - it is not gonna happen. 

maybe we should be perfectly clear that TRTL may reach let's say 0.01$ (as an example), and people shouldnt expect more because it is unreasonable. Or maybe we should set up a target price we are aiming at.
just a suggestion.

**Comment by SoreGums** [comment]
Hi there, curious where this target price idea is coming from in the first place for you.

The price should reflect usefulness to people, the utility of the TurtleCoin's existence is what gives it value. This is how any currency should work be it fiat or crypto, likewise could be extended to assets and commodities, basically anything of exchangeable value.

So I'm genuinely curious why you want a _target value_ to be a thing, this is not something I'm familiar with or come across yet.

**Comment by holytastyguacamole** [comment]
Hey @ghua78,

I think you may be missing the point with the idea of a target price. First off, you are making two assumptions in your price hypothesis which are incorrect.
1. TRTL will not surpass BTC - Unlikely, but not impossible
2. TRTL will never reach $1 - Highly unlikely, but not impossible

In economics, the price of something is always comes from supply vs demand. If the demand for TRTL is **higher** than the supply, the price will rise. If the demand for TRTL is **lower** than supply, the price will fall. For instance, current supply is approximately 6.6billion, if _(granted it is a big IF)_ 6.6billion around the wold woke up tomorrow and wanted/needed to use 10 TRTL what would happen to the price?

A more worthwhile pursuit for us early users is to increase the **demand** for TRTL. Since supply is already locked in, we only have control over the supply side of the equation. To do this, we should focus on:
1. Increasing awareness through our communities
2. Sharing Turtlecoins so more and more people want to hold them
3. Welcoming new users of the technology

Hope that helps.

**Comment by BebopTC** [comment]
developers have no ability to control or effect price (intentionally `effect` as a verb, with the letter `e`), which is determined by market factors. 

to establish and communicate a target value is unethical, would certainly fail the Howey test and make turtlecoin subject to a number of SEC regulations as a security, and would frnakly have no basis on fact or reality.
