### ISSUE TITLE
Double Spend Vulnerability?

### ISSUE THREAD

**Issue by MarQuisKnox** [turtlecoin/meta#75]
Has this issue been resolved w/ Bytecoin & TurtleCoin? 
https://getmonero.org/2017/05/17/disclosure-of-a-major-bug-in-cryptonote-based-currencies.html

![spent_keys](https://user-images.githubusercontent.com/789594/36999778-7da7249a-20c1-11e8-88d4-090553bdbcf9.png)

**Comment by ZedPea** [comment]
Yes. From the article: 

> Note that, at this time, only Monero, Aeon, Boolberry, and Forknote have updated.

Turtlecoin is a fork of forknote. Those warnings are caused by large transactions on the network that are stuck in the transaction pool being resubmitted and your daemon rejecting them. The segmentation faults occur rarely and are hard to debug, probably not related.

**Comment by MarQuisKnox** [comment]
Yeah, but as I understand, TurtleCoin is based on Bytecoin. 
Also from the article:

> We strongly caution against anyone using, trading, exchanging, or running services involving the following currencies affected by this issue: Bytecoin, DashCoin, DigitalNote

**Comment by ZedPea** [comment]
Forknote is a fork of Bytecoin, TurtleCoin is a fork of Forknote. Forknote is patched, so TurtleCoin is patched.

**Comment by RocksteadyTC** [comment]
We are based on Forknote, but regardless of origin, speaking about our initial codebase, this is/was not a vulnerability that affects us.

**Comment by MarQuisKnox** [comment]
Great. 
Thanks!

**Comment by RocksteadyTC** [comment]
The reason you see Transaction uses spent key image is because it is a transaction that is in the memory pool being rebroadcast among nodes. The responses you see are other nodes on the network that already contain record of this transaction broadcasting a status message that says "hey, I already have this one in the queue".

These transactions are usually being rebroadcast because they are stuck due to not enough fee, or too many inputs in one transaction. See this article for more details: **https://medium.com/@turtlecoin/big-turtles-get-stuck-b924aba58445**

**Comment by MarQuisKnox** [comment]
Thanks for the detailed explanation. 
Very informative.
