### ISSUE TITLE
Request Android wallet that can import paper wallets/use google creds/remote daemon/use fingerprint

### ISSUE THREAD

**Issue by fernysalaz** [turtlecoin/meta#77]
I want a turtle coin wallet app for Google Android, where I can put the address of my paper wallet and be able to sync it online, simple, and also integrate fingerprint data to the wallet and also integrate email, so the wallet has its own personal email and I can also log in with my Gmail account for more simplicity and faster access

**Comment by SoreGums** [comment]
nice.

There is a web wallet in the works.
An extension to that could be what you describe.
We'll have to wait and see what fexra does in terms of an API for such apps

**Comment by fexra** [comment]
@fernysalaz 

I'm currently working on a web wallet which will go live soon. The API will allow any developer to make a Android app, but it would only work with addresses registered with the web wallet. I'm afraid supporting the ability to import keys (an address as you described it) won't be possible right now.

**Comment by fernysalaz** [comment]
Well the point is for me to import a paper generated wallet, what is the
point of paper generated wallet then?
None! Obviously, so why even generating them?
Also I don't like those long key lock passwords instead why not just
generating the wallet with a normal password system and also logging with
Google account

**Comment by fernysalaz** [comment]
The Pegasus wallet does allow to add offline Paper wallet for the Stellar
coin, and is very fast coin as well, you should make an app exactly like
it, but also include fingerprint in it will be awesome that way.

**Comment by SoreGums** [comment]
first version: working web wallet
a future version, importing addresses.

(right now, meant when it goes live, afterwards he'll look into what to do next! and would probably look into importing wallets)

the point of paper wallets is they can be used to create an address to receive TRTL to _right now_.
They can be accessed via the cli wallet, I get that is not the most friendly way to interact with these paper wallets, however, they are usable. this project is brand new and is here for the long haul, things not being 100% user-friendly right now is how things are. There is a lot of activity going on to address this user-friendly aspect in the developer community around the TurtleCoin project.

Other uses for the paper wallet:

- create, load up with TRTL, distribute around for people to find, guerilla marketing.
- give TRTL to someone specific, like a gift.
- create an address to use on TurtleCoin's [Discord chat](https://discordapp.com/invite/NZ7QYJA) to catch rain (free TRTL coin)

For right this second, @fernysalaz this is of no use to you for what you want to do, this we acknowledge. I too would like to have similar use case as what you have presented and I am sure others will as well. The things that are most desired will get made, that is how these projects work.

Specifically regarding your "regular password system and login with Google" - totally doable. Of course, there is a slight issue around which entity knows the secrets to your wallet. If you are ok giving these to a third party, the third party will gladly take them. It is all about trade-offs. 

Finally every other project older than this one has features that would be great to add to TurtleCoin, the ones that make sense and a lot people want will make it into this project - it's just how things work :)

**Comment by BebopTC** [comment]
Paper wallets aren't pointless, they can be quickly generated and used to receive payments, to mine to, etc. You have to then import the keys into  **synchronized** wallet tool that has the ability to look at the blockchain and, using the keys of the wallet, be able to decrypt the payments to that wallet. This enables outgoing transactions so that you can spend the holding. 

> Also I don't like those long key lock passwords instead why not just generating the wallet with a normal password system and also logging with Google account

I'm very uncertain what you mean here. A paper wallet has no password, it is just a public/private keyset, that is what a wallet *is*. When you import those keys into a live wallet, you create a password for the wallet file (just like when you generate one in simplewallet or a GUI wallet) that stores those keys locally, to prevent anyone from just grabbing the wallet file and having access to your wallet. You can set any password you like.

There is nothing to log into, not sure how google plays at all into this.

**Comment by BebopTC** [comment]
Also, be certain you understand the difference between an actual **wallet** (which is just a combo of public/private keys), the **wallet software** (e.g. simplewallet) which is often referred to as "wallet", and a **service provider** that provides wallet management (often called a web wallet).

To use the funds in a wallet (i.e. send out transactions), you have to be able to interact with the network and the blockchain, which means you need to have a connection to a running node that has the full blockchain. This is not convenient in many cases, for example on a mobile device with limited storage, and so service providers can prvode a service to hold wallets for you and provide an interface for you to interact/manage the wallet **held and controlled ultimately by the service** - just like funds deposited on an exchange. There is inherent risk there that you should be aware of, as you are relinquishing control to the service provider.

**Comment by SoreGums** [comment]
i am referring to @fexra web wallet when talking about the web wallet :)

**Comment by fernysalaz** [comment]
True that wallets in an app are subject to control by the companies that
handle the OS or specific app, what I am suggesting is a wallet that is
capable of importing the paper wallets into the app, so it allows the
option to send from it, as paper wallet is not capable of connecting online
currently, and neither you can use a paper wallet for sending coins, I am
suggesting an app that allows an easier way to log in, such as fingerprint
and or face ID login, and you can be capable of doing such thing from your
website turtle coin.lol and you can simply make the login webpage as an app
shortcut, so the app can basically open the webpage and also use the
fingerprint, so that way the app is not subject to Androids regulations as
it would be a link to access the wallet and control it, also the wallet
should be made available from a cloud service download, because the wallet
on the website does not work properly, it would not work in the windows 10
desktop nor laptop I have, so there is a problem with the wallet not
functioning properly, and that needs to be fixed, a simple wallet is just
better so we can just log in with fingerprint and import the offline paper
wallets into it and allow the paper wallet to re-regenerate with
fingerprint data and email address log in into it, so it can link the email
to it, much simpler.
They should do that to all paper wallets before getting them, before it
generates the paper wallet it should request the fingerprint data and the
email to associate the email with the wallet and then generating the wallet
with the email as a sync link and fingerprint and or face scan as log in as
well, instead of a long password that is longer to type and harder to
remember

**Comment by SoreGums** [comment]
so I'm guessing English is not your first language.
with that in mind, let's see if we can clear up some concepts.

Android, has applications. Applications are written by developers. Whatever is in an application is controlled by that developer, the developer has access to all data inside their application. This means as a user you need to trust that the developer of an application is doing the right thing regarding your data.

Face ID/Fingerprints/Google (Gmail) accounts. These don't guarantee data security or mean your data is secure. The function of Google accounts and fingerprints is for an application to verify that the person who is accessing data is the same person that created the data in the first place. It is an authentication method.

Just because you authenticated yourself to an application does not equal your data is safe. The developer will always have full access to your data.

Cryptocurrencies and specifically the wallet where coins are accessible (what is used to send coins) are the data being referred to above. This data is in the form of private keys. Once the keys are made available to applications, especially ones connected to the internet, the security of these keys is in question (one can never be 100% sure you are the only person who knows what these keys are). Keeping these private keys safe is a user's number 1 priority. These private keys are standalone items, they work and function the way they work - they can't be changed, if they are linked to something else they are still private keys and still have the exact same properties they had when created (really long strings of characters that humans can't type easily or read or memorise easy).

OK, let's sum up the above quickly

- private keys for wallets need to be kept secret (secure), they are data (really long strings of characters - they can and never will be anything else, never a fingerprint, never an email address, never a face id match).
- apps on Android (anywhere really) don't keep data 100% secret as the developer has full access to the data.
- fingerprints/Google accounts/Face ID DO NOT equal secure data, they are authentication factors for apps usually to allow access to data.

The TurtleCoin paper wallet works 100% of the time when used the way it has been designed to be used. SimpleWallet from turtlecoin.lol works 100% of the time when used the way it has been designed to be used. If you are having trouble using either of these, please join the discord chat ([https://discord.turtlecoin.lol](https://discord.turtlecoin.lol)) and ask in the \#help channel.

Anything that is created to "allow the import of a paper wallet into an app" is an app, developers or companies or whoever wrote that app has access to that data.

A paper wallet = is a reference to a printed piece of paper with private keys on it. that is all that is meant by a paper wallet. you can call it a text file and inside that text file have the private keys. So yes, paper wallets on their own are incapable of sending transactions, because all they are, is private keys (data). These private keys then need to be imported into a wallet application that is connected to the network.

This brings us finally to your proposal. What you are proposing is a wallet spp. Your version says, instead of a password to encrypt the wallet like how SimpleWallet does it, it should be an android app that uses either your Google account (because of Android, difficult to use an Android device without a Google account) or (as well) a Fingerprint or Face ID. This is totally doable, it requires someone to make a wallet that does this. Now our other point further up is you need to trust that the developer of the wallet app on Android is trustworthy, you are giving that developer your private keys (data) to be able to do transactions on the network.

**Hopefully, you realise that we acknowledge your idea as a worthy idea and it would indeed simplify using the TurtleCoin network on Android devices** However the specifics/details of what you wrote do not reflect accurately how TurtleCoin/cryptocurrencies/Android/Apps work.

If what you are proposing did exist, there is a massive disclaimer/caution required to say use at own risk, the developer could steal all your coins at any moment.

OK I'm done :)

**Comment by fernysalaz** [comment]
NO NO NO NO
you are obviously intentionally misinterpreting what I am explaining,
obviously.
The idea of the developer of an app or a wallet, both, either offline paper
generated wallet and or app, doesn't, and is not, IS NOT, in any way force
to be design to allow access for the developer to access the fingerprint
data, you are absolutely wrong in your delusional mind, not even Samsung
has access to your fingerprint data because as long as the data is not
access in the cloud service they provide is not viewable for them, if it's
store in the hardware memory of the device there is no access for them, you
are obviously and completely misleading what I am saying in every single
possible way.
Now here is the other thing you are misleading, because you have a reading
understand problem your system needs to fix right now.
I explain that when generating a paper wallet, you know this, donot act
stupid, you know when generating a paper wallet, the webpage or the app
generates the wallet address, simple to understand, to include the
fingerprint inside the same method of the app or webpage when generating
the wallet, so the data is encrypted with the wallet address, there is no
way for you or any developer to access that data, what you are explaining
is something different that what I am explaining, you are saying for us to
input the data in a log in method, such as a webpage for the developer to
access the data, not what I said, I said that when the wallet is generated
the fingerprint data and the data of the user with email should be input in
the wallet only, so the generating the wallet includes the data not the
developer, there is no way for the developer to access that because the
wallet gathers the data and uses it to generate a new wallet, is the same
method as generating a wallet but with the users data inside, this is
fingerprint data and our own password to log in, rather than the wallet
generating it's own password, we choose to make our own password and then
the wallet is generated with that password and with the data of the
fingerprints as well the email info for cloud sync, either Google or
Facebook, so the paper wallets come with that data in order for us to sync
the wallet and log in easier.

Now here is the other thing I mentioned that you are absolutely changing
nor failing to understand properly, obviously.

The apps, many of them, out there, the developer doesn't necessarily needs
or require to have your data, there is many mechanism in which you can link
a paper wallet with no need to provide the developer that such data,
doesn't exist.
Google doesn't do that, I donot know what developer you are talking about?
You link an email with your app wallet, and the developer only has access
to your common data, such as name and address, there is no way for them to
access your fingerprint data, I like to know which developer does that!
I because I donot know any.
There is also apps that work as viewing wallets, that only allow to access
the data, such as garlic wallet, although they donot have fingerprint tech,
a third party wallet that allow to view the and display the data of the
coins, without having to use the website, and some other apps that donot,
donot and I mean donot allow access of personal data to any developer, you
can make an app that is a simple wallet that allows to sync with the turtle
coin wallet the same way, by login into the wallet via app, if you can
understand that and not intentionally misinterpret, as you did, which is
molesting and annoying, fingerprint doesn't mean is less safe, that is some
ignorance there, extreme ignorance, to think that fingerprint login is less
safe it only depends on what kind of set up your going to have with the
fingerprint log in, obviously if they design it to allow the developer to
access, well yes, they would be able to access, but to make an app that
generates paper wallets and adds the fingerprint and email and additional
data and uses that information to internally generate you a wallet there is
no way for any developer to access that data because is internally made by
the wallet generating mechanism, and you log in with fingerprint and or you
choose your own password as the generating wallet mechanism will not
generate a long password intead we choose our own and it generates the
wallet that way, easy to understand

**Comment by SoreGums** [comment]
end of the day, a wallet gets the private keys. the developer of that wallet has the private keys. be careful where you choose to put your private keys.

**Comment by SoreGums** [comment]
view keys are on the way - this we can agree on right now at least :D

**Comment by SoreGums** [comment]
OK - I get what you mean now.

TurtleCoin and cryptocurrencies don't work like that. Please stop asking for them to work that way. If you really believe they do, then we look forward to seeing your project when it is released.

**Comment by fernysalaz** [comment]
Thanks for your response, sure I understand they currently donot work like
that, that is why is a feature request, because I believe is more simple
and easier to use, more efficient, is not lazzy when is more productive.

**Comment by fexra** [comment]
@fernysalaz the entire point of them is to **not** work like that. What you're proposing means moving from a decentralized mechanism (where the user owns the keys, and thus the coins) to a centralized system where the developer/application holds the access to your coins (eg: CoinBase)

**Comment by fexra** [comment]
@fernysalaz Hmm you will still be tying someone's identify to the keys themselves. I'm not sure if that's very private. Remember, TurtleCoin is a privacy coin, however, what you're proposing is doable. It would be cool to see a proof of concept, but I doubt any of the current devs have the time or are willing to put their time into this request for the time being (yes I used the word time a lot in that sentence :+1: )

**Comment by fernysalaz** [comment]
When it generates a wallet, and hashes the data in it, it can be encrypted
only with the coins network, doesn't have to be anyone's else, an email
address is private, and even if someone else has the email address they
can't log in into the account just by having that address, so I donot know
what you mean when you say is not secure.
So if a give my email address to some then is not secure for me to do so
according to what you are saying.

**Comment by fernysalaz** [comment]
They can make an app that can allow to sync the paper wallet and not be
regulated by anyone, all they have to do is make the simple wallet
generator for it, the same one used in the turtle coin, but just place it
in a free app, and we could use fingerprint and or choose a password or
both either one to log in, either you want to log with password and or with
a fingerprint that is registered prior to generating your wallet.
If someone wanted to that they could do it and not have to give any
information to anyone.

**Comment by fernysalaz** [comment]
The RedCoin wallet works that way,except they donot have fingerprint and or
we donot get to choose a password, but is a free app we can download and it
generates a wallet address and we can use it to send and receive coins, the
can make the same thing but a more sophisticated version of it.

**Comment by ereptor81** [comment]
Thanks for the suggestions Fern. Mobile wallet is likely still a good ways out, but we'll take them into consideration when we begin planning the roadmap for it.

**Comment by BebopTC** [comment]
@fernysalaz either there is a language barrier or you seem to be missing some fundamental aspects of cryptology, particularly as it applies to blockchains and private blockchains. That being said I agree some of us are probably misunderstanding what you are trying to convey, to some extent.

To be clear: there is no such thing as an 'account' in this domain.  You do not "log in" to any service or any thing.

What you refer to as the "long password generated by the wallet" IS THE WALLET. IT IS NOT A PASSWORD. It is a randomly generated private key of an intentional length, used to mathematically derive a public key (the wallet address) in such a way that is intentionally not predictable and intentionally difficult to reverse (i.e. derive the private key from the public key). this is the crux upon which all modern cryptography in use today depends. In TurtleCoin, like other Cryptonote coins, your private key is two parts: the view key and the spend key. They are combined to derive the public address. If you followed a scheme that used your email, fingerprint, or any other identifiable information in a useful (i.e. predictable) way, it would likely significantly reduce the security of the protocol and the privacy. If you want to describe a mechanism in working detail, feel free to publish the white paper or reference one that does.

when you import your ~~wallet~~ private view key and private spend key, the wallet software (e.g. `simplewallet`) *stores the keys* in a file along with other data, and prompts you to *create a password of your own choosing* to **protect that file that has your private keys and data stored in it locally on your computer**. You can make any password you want for that. If you're using hardware that supports fingerprint scanning there's no reason in theory that couldn't be integrated, but it's just a matter of which platforms/APIs to support. In the case of a mobile wallet client, it makes more sense, as the mobile platforms have standardized APIs for fingerprint scanning and tend to have the hardware as well.

There are free apps that will generate and allow you to use a wallet already - simplewallet, the GUI wallets, etc. The issue then is a wallet client for mobile, particularly one that implements the fingerprint scanning (or relying on a 3rd party auth service) as you describe. THAT PART is doable.

It comes down to the issue of having access to the blockchain and being able to sync with it. Because our blockchain is private (every transaction is encrypted and not publicly viewable) for your wallet software to know what funds you have available and be able to emit valid transactions that point back to the incoming transactions that provide the amount you're sending, it must analyze the entire blockchain from the beginning up to the current block and determine all the incoming transactions to your wallet address. As you can imagine, this presents challenges with mobile devices that tend to have less storage, CPU power, and energy available. Even if talking to a remote node so the mobile device doesn't have to store the wallet, it still has to do a lot of chatting back and forth with the node and lots of local processing to determine incoming transactions. It also depends on having the code to do all these things implemented, and right now our actual wallet functionality is implemented only in C++. I don't believe either Android or iOS have native support for c++ at this time. Doing the same in browser as a webapp would require implementations of the wallet functionality in javascript (the langauge browsers support).

So hopefully that clears up that there are preliminary problems that have to be solved for *any* kind of web or mobile wallet to exist, and once solutions are engineered, then we can look into usability features like fingerprint scanning and one-click-ready wallets.  There are some workarounds in the works, for instance the "web wallet" that @fexra is working on, but that works by essentially providing a service that does all the blockchain syncing and wallet management for you, which, in the current stages of development, mean your keys are stored with the 3rd party service and you are then entrusting an unknown 3rd party and compromising some privacy, security, and decentralization features.

A sort of middle-ground solution is similar to waht mymonero.com does - they provide a remote node and some back-end services for doing a lot of the blockchain analysis to determine your balance and incoming funds, which depend on the user sending only their private view key to the service, and the service sends back to your browser the information it extracts. Then, your browser uses your private key locally to send and emit transactions. Personally I think it's elegant but again requires a bit of code we just don't have developed **yet**.

Remember at the core of it, the philosophy of TurtleCoin, like other privacy coins, is that *decentralization*, *privacy*, and *security* are the absolute must-have qualities. We are willing to compromise any convenience, speed, or efficiency necessary to ensure those three qualities, and so sometimes that means we just have to figure out some challenging engineering problems to make things fast and easy.

**Comment by fernysalaz** [comment]
The Dogecoin does something that I explain but it doesn't use fingerprint
Is call
SWEEP PAPER WALLET
And it does something similar to what I explain, where it takes all the
coins from the paper wallet into the online wallet making the paper wallet
useless.
My idea is the same thing, except to include the fingerprint ID in it and
email ID to sync with any other wallet offline it online, and doesnot
compromises anyone's data in anyway possible, and yes is real and does
exist.

There is no need for the private key, because is best for us to choose our
password rather than having a very long private key which makes it harder
to remember, if instead of generating a long password they combine
fingerprint with allowing us to choose our own password this would be much
simpler, because we would be able to choose our password and if we donot
remember the password we could also have fingerprint login as well either,
that way it would generate the wallet more simple and more secure, Sweeping
the wallet is a good idea, but I never used this method so I donot know how
effective it is or it it takes long time to do so.

**Comment by fernysalaz** [comment]
They can also sync the fingerprint and face ID data into the coins network
and have it as a wallet, that way is directly into the network
That way it can link all wallets automatically, as if it was a coin.

**Comment by SoreGums** [comment]
> There is no need for the private key, because is best for us to choose our
password rather than having a very long private key which makes it harder
to remember, if instead of generating a long password they combine
fingerprint with allowing us to choose our own password this would be much
simpler,

This right here is where you are misunderstanding what we have been saying.

The private key is essential/required/fundamental/necessary/important - to get rid of it and only have a user chosen password/fingerprint means that the application keeps the private key, the private key doesn't disappear/vanish/go away...

Again - your actual idea of easy to use, is DOABLE, the way you are describing the details is NOT how it will be done :)

**Comment by SoreGums** [comment]
Absolutely, you are correct, it will be easier to login with only a fingerprint, face id, and for a user to choose their own password. all of this will come into an application in the future, your request has been noted many times.

Are we good now/You feel like we have heard you now?

**Comment by fernysalaz** [comment]
Yes, thanks
