### ISSUE TITLE
Turtlecoin governance, treasury and DAO?

### ISSUE THREAD

**Issue by holytastyguacamole** [turtlecoin/meta#81]
Just curious to know what people's opinion are for a DAO type of governance?

So after watching the [Cardano whiteboard presentation](https://youtu.be/Ja9D0kpksxw?t=2019) by Charles Hoskinson, I looked into the Dash treasury model and in general, it seems like a good idea. i.e. the ability for the network to self fund.

While Turtlecoin is at the very early stages, I think it is worthwhile to have the discussion and if it is even possible to implement in our network. From what I have seen so far, these are some of the pros and cons of such model:

**Pros:**
- Network has less reliance on developers donating their time
- Formal way to reach consensus. Effectively a 'Constitution' for the network
- Projects can be funded via 'democratized' system
- The network essentially reinvests on itself, increasing its sustainability
- There can be an incentive to be a node (currently there is none)
- Solution to the 'tragedy of the commons' problem

**Cons:**
- Masternode system is not private/decentralized  _(Is this system possible without masternodes?)_
- Less likely for people to volunteer their time when others are getting paid
- Seen as a tax on block earnings (Nobody likes taxes)

Let me also add that I do not understand the complexities behind CryptoNote and how the code may or may not lend itself to such a system.

Please lets try to keep the discussion focused on a governance/treasury system for TRTL. Not looking to start a war of words between cryptos.

**Comment by SoreGums** [comment]
The thing with DASH is the masternodes are a core concept in that network. DASH isn't DASH without masternodes. They serve a purpose, they have been built into the network to deliver on that purpose, they are fundamental to what DASH is.

So that automatically throws a spanner in the works in adopting something like that for TRTL. The major downside to the masternode idea/concept is it means the rich get richer and plebs can simple be plebs. Masternodes in DASH require a min balance to become a masternode, as the value of DASH increases the likelihood of someone starting a new masternode is unlikely.

Do I like the masternode/vote thing - yes I do. Would it make sense in TRTL, nope, not now.

Are there other ways to achieve the result? absolutely. 

Build out a system that functions similarly hook it up to #bounties channel in Discord, once Kari comes online hand over control to Kari. In the meantime, pick/vote for stewards to maintain the integrity of the system (the funds are distributed as requested).

The funds come from anyone who wants to fund that particular development.
There is no tax.
It is mostly decentralised enough.
It still attracts ideas / contributors.
Voting is open to everyone.

That is my 2cents

**Comment by brandonlehmann** [comment]
This has been handled via the node fee system introduced in 
- https://github.com/turtlecoin/turtlecoin/pull/417
- https://github.com/turtlecoin/turtlecoin/pull/326
- https://github.com/turtlecoin/turtlecoin/pull/381

**Comment by brandonlehmann** [comment]
More specifically, the incentive to run a node because now public ones can and do charge fees.
