### ISSUE TITLE
Default directory for blockchain in official gui wallet

### ISSUE THREAD

**Issue by Jihadist** [turtlecoin/meta#83]
Hello everyone! Why does wallet use folder on disc C as a default directory for storing blockchain? How can i change it? Maybe not only me have others discs with more space than disc C. So maybe i want to store blockchain on portable hdd. What should i do? Thanx

**Comment by ZedPea** [comment]
It stores on C:/ because it's not guaranteed people have a D:/ drive. You can use a symbolic link to change the location it reads from and move the chain to your D:/ drive.

```
move "C:\Users\(Logon name)\AppData\Roaming\TurtleCoin" "E:\where\you\want\the\chain"
mklink /d "C:\Users\(Logon name)\AppData\Roaming\TurtleCoin" "E:\where\you\want\the\chain" 
```

You can also use the shell extension if command lines aren't your thing, link here: http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

Simply cut the turtlecoin folder from %appdata%\roaming onto another drive where you want it then right click and "Pick link source". Then go to %appdata%\roaming and make sure there isn't a Turtlecoin folder, then right click and "drop as junction"

If you can't get that working, come to our #help channel in discord, and we'll get you sorted out. http://chat.turtlecoin.lol

**Comment by SoreGums** [comment]
looks like this is resolved - windows dev best practices says use %appdata% - so unless gui dev chooses to deviate from this and pass in args to walletd etc or user gets in there and modifies things. data is going to end up in %appdata% wherever that is
