### ISSUE TITLE
New TurtleCoin Wiki Frontend

### ISSUE THREAD

**Issue by Sajo811** [turtlecoin/meta#95]
I've designed a new turtlecoin wiki frontend using mkdocs, optimized for desktop, laptop, mobile etc. etc. n the turtlecoin colours

You can check the website [here](https://turtlewiki.netlify.com) and the source code [here](https://github.com/sajo811/turtledocs)

I propose to overwrite whatever is currently in turtlecoin-wiki with what is in my repo (guide [here](https://github.com/Sajo811/turtledocs#merging-it)).

Or you can make a new branch and put either my frontend or the current wiki on it, so that we have the orig. copy if needed

I know this is a lot to ask, but I feel it is worth it. Many people I've showed it appreciate the design and optimization over the old(current) wiki, tenfold.

Can it be possible? Any suggestions?

**Comment by ar-x** [comment]
The `turtlecoin/turtlecoin-wiki` is [likely](https://github.com/turtlecoin/meta/issues/91) to be renamed to `turtlecoin/turtlecoin-docs` (yes, full circle, but it made sense both times for the same reasons). The intention there is for it to be the authoritative source of *all* knowledge. It would contain User Guides, Developer Guides, API Docs and maybe more in the future. 

One frontend - mkdocs - might not be suited for the presentation for all such doc types, so I think having one repo with the User Guides mkdocs frontend source, and all knowledge docs is not a good idea.

So it would be nice if the frontend can be moved out of the wiki/docs repo.

I think this has already been said else where.

**Comment by Sajo811** [comment]
Yep that's no problem, commands remain the same. We can just rename/make a new repo and let the frontend reside there and be built from there

**Comment by SoreGums** [comment]
You've done great work there @Sajo811

The effort you've put in and the result produced is of great value especially in the current docs accessibility and friendliness of the layout etc.

In terms of replacing the current source of truth with your project, I don't think that is the best path to take when considering the overall TurtleCoin goals and needs with regards to "sometime for all TurtleCoin documentation".

As has been discussed in other places and as stated in the Readme on the current repo, we need a straightforward single source of truth for all docs, not only user guides and how to. so the status quo of [gfm](https://github.github.com/gfm/) arranged nicely in directories in that repo and other repos generating pretty versions of it is probably going to be the way forward. This could change in the future, right now though, probably not.

So if you're able to, figure out a way to get the current repo to run through the mkdocs generator and produce what you've done. Now you understand how it all works this should be a fairly straight forward process. if you get stuck please sing out with a specific question in Discord and I'm sure someone or myself will be able to assist (example: Mkdocs needs x, I've got y I had a go at z, however I'm not getting anywhere close to x here is what I've done [link to thing done], halp me :turtle: ")

others who have different opinions please share :)

**Comment by ar-x** [comment]
My understanding:

* I think a frontend is highly desirable.
* `turtlecoin/docs` would just be content/data. With the GH wiki being an important but interim frontend. Writing content in markdown does limit the frontend design, since markdown leads to HTML, not a proper data structure which can be used by frontend frameworks. But I think thats OK.
* It would be ideal if the GH wiki frontend and the other frontend can be run in junction for a while, and then we deprecate the wiki frontend.

**Comment by Sajo811** [comment]
@SoreGums So why not make a seperate repo for this frontend, where PR's can be made and it is auto built from?

Also I don't think I can make an auto generator; not only do I have nowhere near the level of coding proficiency needed, there are too many fundamental changes to be made which I don't think can be automated in a script.

* links to be changed
* making of new files
* capitalisation of files
* proper formatting, following strict md, not gfm
* installation of mkdocs (and material)

and more. Of course, it is possible that these changes can be made in the current wiki and it is a relatively simple process to make it into a mkdocs thing, but that may break compatibility with the GH wiki, and if you're doing that, then why not import the whole thing?

Another idea ive been thinking about is making the turtlecoin-wiki repo, or someother repo, doesn't matter, have only markdown files in their subdirectories, so it's easy for people to contribute to it. If these are changed, then we can use a webhook or something to cherry-pick commits or something to another repo where the mkdocs and material stuff are - not very user friendly. Then from this repo, it is auto built

Any thoughts? If such a thing is to happen then I will not have the time to work on it till ~July-August

**Comment by SoreGums** [comment]
separate frontend mkdocs generator repo is totally fine, that's the way everything is done, in separate repos. your op proposal is "replace the current repo with yours" so that's what I'm responding to :)

If you provide a name and ask rocksteadytc he'll fork your repo and you can keep going in turtlecoin/project repo.

I haven't had time to review the changes tbh @Sajo811

I get that there are differences between gfm and others. I'm still of the belief that gfm can be transformed into whatever because it is so specific, the only thing on your list is "new files" again though if that is derived from something it could be machined too.

going forward
- see how you go keeping it up to date
- ask Rock for an org fork
- ask Rock to setup a subdomain on turtlecoin.lol

hope this is helpful and gives some options to move forward. if not bring it up and perhaps @BebopTC @RockSteadyTC or others have other ideas.

**Comment by Sajo811** [comment]
I guess I'll have to keep doing cherry-picks for now :/

Thanks, can this become the new production wiki?

Also is turtledocs alright? Won't clash with any planned names? :D

**Comment by Sajo811** [comment]
Knock yourself out! ;D

**Comment by Sajo811** [comment]
By the way, my repository has been forked to [turtlecoin/sajodocs](https://github.com/turtlecoin/sajodocs) and deployed [here](https://docs.turtlecoin.lol), so I feel it is alright to close this issue
